site_name: Unnamed Engine Documentation
site_description: Unnamed Engineのドキュメント
site_url: https://mizuhamineec.github.io/UnnamedEngine/

theme:
  # テーマの指定
  name: material

  # 色の設定
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  # フォントの設定
  font:
    text: "Noto Sans JP"
    code: "JetBrains Mono"

  # アイコンの設定
  logo: assets/logo.svg

  # ファビコンの設定
  favicon: assets/logo.svg

  language: ja
  features:
    - toc.integrate
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - ホーム: 
      - index.md
  - はじめに:
      - gettingstarted.md
      - system-requirements.md
      - setup.md
      - how-to-launch.md
  - ステータス:
      - status.md
  - 基本概念:
      - エンティティ: 
        - entity.md
      - コンポーネント:
        - component.md
        - transformcomponent.md
  - エンジン内蔵コンポーネント: 
    - engine-components.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences: